# Generated by Django 5.2.1 on 2025-06-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='www.category'),
        ),
    ]
