# Generated by Django 5.2.1 on 2025-06-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
